# Generated by Django 3.1.7 on 2021-03-24 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntrinsicValuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('discount_rate', models.FloatField(help_text='i.e. 0.1')),
                ('pe', models.FloatField(help_text='i.e. 33.86')),
                ('eps', models.FloatField(help_text='i.e. 50.45')),
                ('growth_one_year', models.FloatField(help_text='i.e. 0.1')),
                ('growth_five_years', models.FloatField(help_text='i.e. 0.1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.FloatField(help_text='i.e. 10000')),
                ('tickers', models.CharField(max_length=200, null=True)),
                ('sp', models.BooleanField(default=False, verbose_name='S&P500')),
                ('nasdaq', models.BooleanField(default=False, verbose_name='NASDAQ-100')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Period')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End Period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysisFinviz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('day', models.IntegerField(default=datetime.date.today, verbose_name='Days To Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysisReddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20)),
                ('client_secret', models.CharField(max_length=50)),
                ('user_agent', models.CharField(max_length=20)),
                ('subreddits', models.CharField(max_length=100)),
                ('filter_selfpost', models.BooleanField(default=False, verbose_name='selfpost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockForecastSVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('day', models.IntegerField(default=3, verbose_name='Days to predict')),
                ('year', models.DateField(default=datetime.date.today, verbose_name='Analyzing Year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
