# Generated by Django 3.1.7 on 2021-03-06 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockforecastsvm',
            name='day',
            field=models.IntegerField(default=3, verbose_name='Days to predict'),
        ),
    ]
