# Generated by Django 3.1.7 on 2021-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioanalyzer',
            name='tickers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
