# Generated by Django 3.1.6 on 2021-02-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210218_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioanalyzer',
            name='sp500',
        ),
        migrations.AddField(
            model_name='portfolioanalyzer',
            name='sp',
            field=models.BooleanField(default=True, verbose_name='S&P500'),
        ),
        migrations.AlterField(
            model_name='portfolioanalyzer',
            name='dow',
            field=models.BooleanField(default=False, verbose_name='DOW1000'),
        ),
    ]
