# Generated by Django 3.1.6 on 2021-02-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210218_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioanalyzer',
            name='funds',
        ),
        migrations.AddField(
            model_name='portfolioanalyzer',
            name='fund',
            field=models.FloatField(default=10000, help_text='i.e. 10000'),
        ),
        migrations.AlterField(
            model_name='portfolioanalyzer',
            name='dow',
            field=models.BooleanField(default=False, verbose_name='DOW'),
        ),
    ]
