# Generated by Django 3.1.7 on 2021-02-21 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioanalyzer',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Period'),
        ),
        migrations.AddField(
            model_name='portfolioanalyzer',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Period'),
        ),
        migrations.AlterField(
            model_name='portfolioanalyzer',
            name='fund',
            field=models.FloatField(help_text='i.e. 10000'),
        ),
        migrations.AlterField(
            model_name='portfolioanalyzer',
            name='sp',
            field=models.BooleanField(default=False, verbose_name='S&P500'),
        ),
    ]
