# Generated by Django 3.1.7 on 2021-02-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stockforecastsvm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioanalyzer',
            name='dow',
        ),
        migrations.AddField(
            model_name='portfolioanalyzer',
            name='nasdaq',
            field=models.BooleanField(default=False, verbose_name='NASDAQ-100'),
        ),
    ]
