# Generated by Django 3.1.7 on 2021-02-27 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210225_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('day', models.IntegerField(default=datetime.date.today, verbose_name='Days To Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
