name: Publish Docker image
on:
  push:
    branches:
      - main
    paths:
      - 'Algotrading/**'
jobs:
  push_to_registries:
    name: Push Docker image to Github Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        run: |
          docker build  -t docker.pkg.github.com/kriskirla/Algotrading:latest ./Algotrading
          docker push docker.pkg.github.com/kriskirla/Algotrading:latest