name: Publish Docker image
on:
  push:
    branches:
      - main
    paths:
      - 'Algotrading/**'
jobs:
  push_to_registries:
    name: Push Docker image to Github Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
      - name: Build container image
        run: |
          docker build  -t docker.pkg.github.com/kriskirla/algotrading:latest ./Algotrading
          docker push docker.pkg.github.com/kriskirla/algotrading:latest 